### ISSUE TITLE
Twitch.tv failed to connect

### ISSUE THREAD

**Issue by oldage** [charnet3d/DesktopLiveStreamer#2]
I think you have to update something, it's telling me I cannot connect and that I have to check my connection and firewall, while it worked fine a while ago. (and I didn't change anything)

**Comment by charnet3d** [comment]
I'm aware of it, I think it has to do with own3d being shut down... I will address this as soon as this thuesday, as I have an assignment to do for school this monday,

**Comment by charnet3d** [comment]
Okey, I thought that I shouldn't make you wait that long for a small hotfix I can make in 30 minutes so there it is, check the latest version ;)

**Comment by oldage** [comment]
Thanks!
