### ISSUE TITLE
streams not playing. There is a grayed out quality section

### ISSUE THREAD

**Issue by gammmae105** [charnet3d/DesktopLiveStreamer#4]
when clicking "Play," it loads but nothing happens, then after a few seconds "Desktop live streamer has stopped working" windows error. Also noticed the quality drop-down box is grayed out, so I'm assuming it's not able to locate the quality of a stream. 

Here's an imgur image: http://i.imgur.com/xmntecB.png
![error](https://f.cloud.github.com/assets/5284143/1006684/d8458f6c-0aec-11e3-9969-bd0354d2ce1a.png)

**Comment by rockjock51** [comment]
I'm also having this problem.  I'm on Windows 8.1, if it helps.

**Comment by charnet3d** [comment]
This is fixed now in the new 0.9.3 version, check out the read me file ! ;)

**Comment by gammmae105** [comment]
Thanks :)
