### ISSUE TITLE
No quality options and crash on play

### ISSUE THREAD

**Issue by ghost** [charnet3d/DesktopLiveStreamer#5]
Hi there,

hope there's a fix for this.

I think this is due to twitch.tv rewording thier quality options but Im using the 9.3.0 release and when I choose a stream, I dont see any quality options and clicking play makes the app crash.

I tried using the original version of the application, the one without the GUI but for some reason streams lag horribly using that..

**Comment by charnet3d** [comment]
Hi there, I've finally opened the project and decided to update it again... Check out the new version, it solved a few of the problems with the qualities.

**Comment by ghost** [comment]
You're the boss man!
 
-Imad Malik

On Saturday, December 21, 2013 10:20 PM, Charaf Errachidi notifications@github.com wrote:

Hi there, I've finally opened the project and decided to update it again... Check out the new version, it solved a few of the problems with the qualities.
