### ISSUE TITLE
When i press play, it doesnt play anything

### ISSUE THREAD

**Issue by Mortef** [charnet3d/DesktopLiveStreamer#6]
Hi, i just installed desktop live streamer, but when i click play it says loading stream, then ready but nothing happen, doesnt open VLC, i just installed the latest version of VLC but still nothing happen, i have no problem using the open in browser button, but the play button just doesnt open VLC.

Thx.

**Comment by TheJoker93** [comment]
Same here. Please help! Thank you!!

**Comment by christopherdriscoll** [comment]
Also experiencing the same issue with the 9.3 build.

Disregard, I just had to select a different video quality before hitting Play.

**Comment by charnet3d** [comment]
Hi there, I've finally opened the project and decided to update it again... The new version solved a few of the problems with the qualities. Check to see if it works fine now :)
