### ISSUE TITLE
Stuck at loading quality

### ISSUE THREAD

**Issue by orangenod18** [charnet3d/DesktopLiveStreamer#7]
<a href="http://imgur.com/lfmTG36"><img src="http://i.imgur.com/lfmTG36.jpg" title="Hosted by imgur.com"/></a>

It has been long the qualities for too long, any fix for that?

**Comment by charnet3d** [comment]
Hi there, I've finally opened the project and decided to update it again... The new version solved a few of the problems with the qualities. Check to see if it works fine now :)
