### ISSUE TITLE
Need an update

### ISSUE THREAD

**Issue by Tragy** [charnet3d/DesktopLiveStreamer#8]
Hi, i really enjoy your work and what you made it makes my stream waching/recording so easy but twitch made some few updates in last months and desktop live streamer is outdated now.

few issues:
1. problems with connecting to streams
2. problems with quality and loading time for them
3. sometimes program bugs and you need to restart it to watch streams 

tnx for great work i would donate for you if i had to becouse there is no other prog like this simple and classy :dancer:

**Comment by charnet3d** [comment]
Hi Tragy, I've finally opened the project and decided to update it again... The new version solved a few of the problems with the qualities while also adding a new feature that makes it remember the last used quality. Check to see if it works fine now :)
Don't hesitate to report any other problems that remain, I'll try to be more reactive next time ;)

**Comment by Tragy** [comment]
damn great job tnx a lot for your work i saw you stream lol sometimes i
could promote you in my youtube channel if you want tnx your made program i
gave 3k subscribers :)

**Comment by charnet3d** [comment]
Well I stopped playing and streaming LoL recently, it was one of the reasons why I couldn't find the time to update the project. Too much time consumed and no productivity xd
